Added test of json writer which crashed on array of struct with pointer
wc-duck/datalibrary pull request #144
Opened 2022-10-06 13:26 UTC by Tisten

And fixed the crash

The bug here was the fall through on old line 651

This PR also fixes a crash where unions weren't checked in `dl_txt_unpack_write_subdata()`

2022-10-06 20:10 UTC, wc-duck commented
Trying to look at this on my phone... kind of impossible so I'll have to check it out tomorrow:D

2022-10-07 07:43 UTC, Tisten commented
No hurry at all.
The fixes are done, so I'm making these PRs to avoid diverging my fork from your main branch over time, and to get feedback to improve my code. ;)

2022-10-09 15:01 UTC, wc-duck requested changes

2022-10-09 15:01 UTC, wc-duck commented on src/dl_txt_unpack.cpp
> +		assert(size_t((struct_data + type_offset) - unpack_ctx->packed_instance) < unpack_ctx->packed_instance_size);
see https://github.com/wc-duck/datalibrary/#asserts

2022-10-10 17:59 UTC, wc-duck approved these changes

2022-10-10 17:59 UTC, merged